### ISSUE TITLE
autoload.php functionality

### ISSUE THREAD

**Issue by sebosp** [PxxBxx/scte35-parser-php#1]
Hi,

Thanks for sharing the code! I was reading through it and see you are using a vendor/autoload.php. would you mind explaining what is the functionality of this file?

Thanks in advance.

**Comment by arrebatosl** [comment]
Hi,

This code is great!
Would you be able to provide the autoload.php file?

Thanks in advanced,
Viviana

**Comment by PxxBxx** [comment]
Hello ! glad to see people looking forward this parser.
For the vendor/autoload.php, you have to invoke the composer command (https://getcomposer.org/), a classic PHP dependencies injector, you can find it on all major repos (eg. `apt install composer`)
* clone the project `git clone https://github.com/PxxBxx/scte35-parser-php.git`
* go into the project's dir `cd scte35-parser-php`
* execute `composer install` -> it will populate the required dependencies (chdemko/bitarray to work with bit arrays) into vendors/ and create the autoload.php automatically
* everything is working, you can use the parser
